package com.millionaire.compound.hibernate.entity.basic;// default package
// Generated Mar 15, 2021, 9:10:43 PM by Hibernate Tools 4.0.0.Final


import javax.persistence.*;

/**
 * MiracleIndex generated by hbm2java
 */
@Entity
@Table(name="miracle_index"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="ticker") 
)
public class MiracleIndex  implements java.io.Serializable {



     private int id;
     private String ticker;
     private String description;

    public MiracleIndex() {
    }

    public MiracleIndex(int id, String ticker, String description) {
       this.id = id;
       this.ticker = ticker;
       this.description = description;
    }
   
     @Id

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ticker", unique=true, nullable=false)
    public String getTicker() {
        return this.ticker;
    }
    
    public void setTicker(String ticker) {
        this.ticker = ticker;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


