package com.millionaire.compound.hibernate.entity.basic;// default package
// Generated Mar 15, 2021, 9:10:43 PM by Hibernate Tools 4.0.0.Final


import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * MiracleIndexDailyPrice generated by hbm2java
 */
@Entity
@Table(name="miracle_index_daily_price"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ticker", "date"}) 
)
public class MiracleIndexDailyPrice  implements java.io.Serializable {


     private int id;
     private String ticker;
     private Date date;
     private BigDecimal open;
     private BigDecimal close;
     private BigDecimal high;
     private BigDecimal low;
     private BigDecimal range;
     private long volume;
     private long avg5Volume;
     private long avg10Volume;
     private long avg20Volume;
     private long avg30Volume;
     private long avg60Volume;
     private BigDecimal ma5;
     private BigDecimal ma10;
     private BigDecimal ma20;
     private BigDecimal ma30;
     private BigDecimal ma60;

    public MiracleIndexDailyPrice() {
    }

    public MiracleIndexDailyPrice(int id, String ticker, Date date, BigDecimal open, BigDecimal close, BigDecimal high, BigDecimal low, BigDecimal range, long volume, long avg5Volume, long avg10Volume, long avg20Volume, long avg30Volume, long avg60Volume, BigDecimal ma5, BigDecimal ma10, BigDecimal ma20, BigDecimal ma30, BigDecimal ma60) {
       this.id = id;
       this.ticker = ticker;
       this.date = date;
       this.open = open;
       this.close = close;
       this.high = high;
       this.low = low;
       this.range = range;
       this.volume = volume;
       this.avg5Volume = avg5Volume;
       this.avg10Volume = avg10Volume;
       this.avg20Volume = avg20Volume;
       this.avg30Volume = avg30Volume;
       this.avg60Volume = avg60Volume;
       this.ma5 = ma5;
       this.ma10 = ma10;
       this.ma20 = ma20;
       this.ma30 = ma30;
       this.ma60 = ma60;
    }
   
     @Id

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ticker", nullable=false)
    public String getTicker() {
        return this.ticker;
    }
    
    public void setTicker(String ticker) {
        this.ticker = ticker;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=13)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="open", nullable=false, precision=131089, scale=0)
    public BigDecimal getOpen() {
        return this.open;
    }
    
    public void setOpen(BigDecimal open) {
        this.open = open;
    }

    
    @Column(name="close", nullable=false, precision=131089, scale=0)
    public BigDecimal getClose() {
        return this.close;
    }
    
    public void setClose(BigDecimal close) {
        this.close = close;
    }

    
    @Column(name="high", nullable=false, precision=131089, scale=0)
    public BigDecimal getHigh() {
        return this.high;
    }
    
    public void setHigh(BigDecimal high) {
        this.high = high;
    }

    
    @Column(name="low", nullable=false, precision=131089, scale=0)
    public BigDecimal getLow() {
        return this.low;
    }
    
    public void setLow(BigDecimal low) {
        this.low = low;
    }

    
    @Column(name="range", nullable=false, precision=131089, scale=0)
    public BigDecimal getRange() {
        return this.range;
    }
    
    public void setRange(BigDecimal range) {
        this.range = range;
    }

    
    @Column(name="volume", nullable=false)
    public long getVolume() {
        return this.volume;
    }
    
    public void setVolume(long volume) {
        this.volume = volume;
    }

    
    @Column(name="avg5_volume", nullable=false)
    public long getAvg5Volume() {
        return this.avg5Volume;
    }
    
    public void setAvg5Volume(long avg5Volume) {
        this.avg5Volume = avg5Volume;
    }

    
    @Column(name="avg10_volume", nullable=false)
    public long getAvg10Volume() {
        return this.avg10Volume;
    }
    
    public void setAvg10Volume(long avg10Volume) {
        this.avg10Volume = avg10Volume;
    }

    
    @Column(name="avg20_volume", nullable=false)
    public long getAvg20Volume() {
        return this.avg20Volume;
    }
    
    public void setAvg20Volume(long avg20Volume) {
        this.avg20Volume = avg20Volume;
    }

    
    @Column(name="avg30_volume", nullable=false)
    public long getAvg30Volume() {
        return this.avg30Volume;
    }
    
    public void setAvg30Volume(long avg30Volume) {
        this.avg30Volume = avg30Volume;
    }

    
    @Column(name="avg60_volume", nullable=false)
    public long getAvg60Volume() {
        return this.avg60Volume;
    }
    
    public void setAvg60Volume(long avg60Volume) {
        this.avg60Volume = avg60Volume;
    }

    
    @Column(name="ma5", nullable=false, precision=131089, scale=0)
    public BigDecimal getMa5() {
        return this.ma5;
    }
    
    public void setMa5(BigDecimal ma5) {
        this.ma5 = ma5;
    }

    
    @Column(name="ma10", nullable=false, precision=131089, scale=0)
    public BigDecimal getMa10() {
        return this.ma10;
    }
    
    public void setMa10(BigDecimal ma10) {
        this.ma10 = ma10;
    }

    
    @Column(name="ma20", nullable=false, precision=131089, scale=0)
    public BigDecimal getMa20() {
        return this.ma20;
    }
    
    public void setMa20(BigDecimal ma20) {
        this.ma20 = ma20;
    }

    
    @Column(name="ma30", nullable=false, precision=131089, scale=0)
    public BigDecimal getMa30() {
        return this.ma30;
    }
    
    public void setMa30(BigDecimal ma30) {
        this.ma30 = ma30;
    }

    
    @Column(name="ma60", nullable=false, precision=131089, scale=0)
    public BigDecimal getMa60() {
        return this.ma60;
    }
    
    public void setMa60(BigDecimal ma60) {
        this.ma60 = ma60;
    }

    @Override
    public String toString() {
        return "MiracleIndexDailyPrice{" +
                "ticker='" + ticker + '\'' +
                ", date=" + date +
                ", open=" + open +
                ", close=" + close +
                ", high=" + high +
                ", low=" + low +
                ", range=" + range +
                ", volume=" + volume +
                ", avg5Volume=" + avg5Volume +
                ", avg10Volume=" + avg10Volume +
                ", avg20Volume=" + avg20Volume +
                ", avg30Volume=" + avg30Volume +
                ", avg60Volume=" + avg60Volume +
                ", ma5=" + ma5 +
                ", ma10=" + ma10 +
                ", ma20=" + ma20 +
                ", ma30=" + ma30 +
                ", ma60=" + ma60 +
                '}';
    }
}


