package com.millionaire.compound.hibernate.entity.basic;// default package
// Generated Apr 4, 2021, 11:07:40 PM by Hibernate Tools 4.0.0.Final


import javax.persistence.*;
import java.math.BigDecimal;

/**
 * MiracleStock generated by hbm2java
 */
@Entity
@Table(name="miracle_stock"
    ,schema="public"
)
public class MiracleStock implements java.io.Serializable {


     private int id;
     private String ticker;
     private String category;
     private String sector;
     private String companyName;
     private String industry;
     private BigDecimal oneYrTarget;
     private BigDecimal forwardPe1yr;
     private BigDecimal marketCap;
     private BigDecimal pe;
     private BigDecimal earning;
     private BigDecimal eps;
     private BigDecimal dividend;
     private BigDecimal yield;
     private BigDecimal beta;
     private String nextReportDate;
     private String url;

    public MiracleStock() {
    }

    public MiracleStock(int id, String ticker, String category, String sector, String companyName, String industry, BigDecimal oneYrTarget, BigDecimal forwardPe1yr, BigDecimal marketCap, BigDecimal pe, BigDecimal earning, BigDecimal eps, BigDecimal dividend, BigDecimal yield, BigDecimal beta, String nextReportDate, String url) {
       this.id = id;
       this.ticker = ticker;
       this.category = category;
       this.sector = sector;
       this.companyName = companyName;
       this.industry = industry;
       this.oneYrTarget = oneYrTarget;
       this.forwardPe1yr = forwardPe1yr;
       this.marketCap = marketCap;
       this.pe = pe;
       this.earning = earning;
       this.eps = eps;
       this.dividend = dividend;
       this.yield = yield;
       this.beta = beta;
       this.nextReportDate = nextReportDate;
       this.url = url;
    }
   
     @Id

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ticker", nullable=false)
    public String getTicker() {
        return this.ticker;
    }
    
    public void setTicker(String ticker) {
        this.ticker = ticker;
    }

    
    @Column(name="category", nullable=false)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="sector", nullable=false)
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }

    
    @Column(name="company_name", nullable=false)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    
    @Column(name="industry", nullable=false)
    public String getIndustry() {
        return this.industry;
    }
    
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    
    @Column(name="oneyrtarget", nullable=false, precision=131089, scale=0)
    public BigDecimal getOneYrTarget() {
        return this.oneYrTarget;
    }
    
    public void setOneYrTarget(BigDecimal oneYrTarget) {
        this.oneYrTarget = oneYrTarget;
    }

    
    @Column(name="forwardpe1yr", nullable=false, precision=131089, scale=0)
    public BigDecimal getForwardPe1yr() {
        return this.forwardPe1yr;
    }
    
    public void setForwardPe1yr(BigDecimal forwardPe1yr) {
        this.forwardPe1yr = forwardPe1yr;
    }

    
    @Column(name="market_cap", nullable=false, precision=131089, scale=0)
    public BigDecimal getMarketCap() {
        return this.marketCap;
    }
    
    public void setMarketCap(BigDecimal marketCap) {
        this.marketCap = marketCap;
    }

    
    @Column(name="pe", nullable=false, precision=131089, scale=0)
    public BigDecimal getPe() {
        return this.pe;
    }
    
    public void setPe(BigDecimal pe) {
        this.pe = pe;
    }

    
    @Column(name="earning", nullable=false, precision=131089, scale=0)
    public BigDecimal getEarning() {
        return this.earning;
    }
    
    public void setEarning(BigDecimal earning) {
        this.earning = earning;
    }

    
    @Column(name="eps", nullable=false, precision=131089, scale=0)
    public BigDecimal getEps() {
        return this.eps;
    }
    
    public void setEps(BigDecimal eps) {
        this.eps = eps;
    }

    
    @Column(name="dividend", nullable=false, precision=131089, scale=0)
    public BigDecimal getDividend() {
        return this.dividend;
    }
    
    public void setDividend(BigDecimal dividend) {
        this.dividend = dividend;
    }

    
    @Column(name="yield", nullable=false, precision=131089, scale=0)
    public BigDecimal getYield() {
        return this.yield;
    }
    
    public void setYield(BigDecimal yield) {
        this.yield = yield;
    }

    
    @Column(name="beta", nullable=false, precision=131089, scale=0)
    public BigDecimal getBeta() {
        return this.beta;
    }
    
    public void setBeta(BigDecimal beta) {
        this.beta = beta;
    }

    
    @Column(name="next_report_date", nullable=false)
    public String getNextReportDate() {
        return this.nextReportDate;
    }
    
    public void setNextReportDate(String nextReportDate) {
        this.nextReportDate = nextReportDate;
    }

    
    @Column(name="url", nullable=false)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


