package com.millionaire.compound.hibernate.entity.basic;// default package
// Generated Jan 6, 2021, 10:10:56 PM by Hibernate Tools 4.0.0.Final


import javax.persistence.*;
import java.math.BigDecimal;

/**
 * MiracleStock generated by hbm2java
 */
@Entity
@Table(name="miracle_stock"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="ticker") 
)
public class MiracleStock implements java.io.Serializable {


     private int id;
     private String ticker;
     private String category;
     private String company;
     private String companyName;
     private BigDecimal avg3mVolumn;
     private BigDecimal yearRange;
     private String w52Range;
     private BigDecimal marketCap;
     private BigDecimal cirMarketCap;
     private BigDecimal pe;
     private BigDecimal earning;
     private BigDecimal eps;
     private BigDecimal forwardDividend;
     private BigDecimal yield;
     private BigDecimal beta;
     private String nextReportDate;

    public MiracleStock() {
    }

    public MiracleStock(int id, String ticker, String category, String company, String companyName, BigDecimal avg3mVolumn, BigDecimal yearRange, String w52Range, BigDecimal marketCap, BigDecimal cirMarketCap, BigDecimal pe, BigDecimal earning, BigDecimal eps, BigDecimal forwardDividend, BigDecimal yield, BigDecimal beta, String nextReportDate) {
       this.id = id;
       this.ticker = ticker;
       this.category = category;
       this.company = company;
       this.companyName = companyName;
       this.avg3mVolumn = avg3mVolumn;
       this.yearRange = yearRange;
       this.w52Range = w52Range;
       this.marketCap = marketCap;
       this.cirMarketCap = cirMarketCap;
       this.pe = pe;
       this.earning = earning;
       this.eps = eps;
       this.forwardDividend = forwardDividend;
       this.yield = yield;
       this.beta = beta;
       this.nextReportDate = nextReportDate;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ticker", unique=true, nullable=false)
    public String getTicker() {
        return this.ticker;
    }
    
    public void setTicker(String ticker) {
        this.ticker = ticker;
    }

    
    @Column(name="category", nullable=false)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    @Column(name="company", nullable=false)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    
    @Column(name="company_name", nullable=false)
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    
    @Column(name="avg3m_volumn", nullable=false, precision=15, scale=4)
    public BigDecimal getAvg3mVolumn() {
        return this.avg3mVolumn;
    }
    
    public void setAvg3mVolumn(BigDecimal avg3mVolumn) {
        this.avg3mVolumn = avg3mVolumn;
    }

    
    @Column(name="year_range", nullable=false, precision=5, scale=4)
    public BigDecimal getYearRange() {
        return this.yearRange;
    }
    
    public void setYearRange(BigDecimal yearRange) {
        this.yearRange = yearRange;
    }

    
    @Column(name="w52_range", nullable=false)
    public String getW52Range() {
        return this.w52Range;
    }
    
    public void setW52Range(String w52Range) {
        this.w52Range = w52Range;
    }

    
    @Column(name="market_cap", nullable=false, precision=15, scale=4)
    public BigDecimal getMarketCap() {
        return this.marketCap;
    }
    
    public void setMarketCap(BigDecimal marketCap) {
        this.marketCap = marketCap;
    }

    
    @Column(name="cir_market_cap", nullable=false, precision=15, scale=4)
    public BigDecimal getCirMarketCap() {
        return this.cirMarketCap;
    }
    
    public void setCirMarketCap(BigDecimal cirMarketCap) {
        this.cirMarketCap = cirMarketCap;
    }

    
    @Column(name="pe", nullable=false, precision=5, scale=4)
    public BigDecimal getPe() {
        return this.pe;
    }
    
    public void setPe(BigDecimal pe) {
        this.pe = pe;
    }

    
    @Column(name="earning", nullable=false, precision=15, scale=4)
    public BigDecimal getEarning() {
        return this.earning;
    }
    
    public void setEarning(BigDecimal earning) {
        this.earning = earning;
    }

    
    @Column(name="eps", nullable=false, precision=5, scale=4)
    public BigDecimal getEps() {
        return this.eps;
    }
    
    public void setEps(BigDecimal eps) {
        this.eps = eps;
    }

    
    @Column(name="forward_dividend", nullable=false, precision=5, scale=4)
    public BigDecimal getForwardDividend() {
        return this.forwardDividend;
    }
    
    public void setForwardDividend(BigDecimal forwardDividend) {
        this.forwardDividend = forwardDividend;
    }

    
    @Column(name="yield", nullable=false, precision=5, scale=4)
    public BigDecimal getYield() {
        return this.yield;
    }
    
    public void setYield(BigDecimal yield) {
        this.yield = yield;
    }

    
    @Column(name="beta", nullable=false, precision=5, scale=4)
    public BigDecimal getBeta() {
        return this.beta;
    }
    
    public void setBeta(BigDecimal beta) {
        this.beta = beta;
    }

    
    @Column(name="next_report_date", nullable=false)
    public String getNextReportDate() {
        return this.nextReportDate;
    }
    
    public void setNextReportDate(String nextReportDate) {
        this.nextReportDate = nextReportDate;
    }




}


